# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QInputDialog, QFileDialog

import os
os.environ['TF_CPP_MIN_LOG_LEVEL']='3' # or any 0,1,2
import numpy as np 
import tensorflow as tf 
tf.compat.v1.logging.set_verbosity(tf.compat.v1.logging.ERROR)
from keras.preprocessing import image
from keras_preprocessing.image import ImageDataGenerator


class Ui_MainWindow(object):
    filename = None
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(774, 448)
        MainWindow.setMinimumSize(QtCore.QSize(774, 448))
        MainWindow.setMaximumSize(QtCore.QSize(774, 448))
        MainWindow.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(270, 30, 271, 71))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(300, 90, 241, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btn_choose = QtWidgets.QPushButton(self.centralwidget)
        self.btn_choose.setGeometry(QtCore.QRect(420, 250, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_choose.setFont(font)
        self.btn_choose.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.btn_choose.setObjectName("btn_choose")
        self.btn_choose.clicked.connect(self.open_fileDialog)
        self.btn_predict = QtWidgets.QPushButton(self.centralwidget)
        self.btn_predict.setGeometry(QtCore.QRect(330, 310, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.btn_predict.setFont(font)
        self.btn_predict.setStyleSheet("background-color: rgb(222, 222, 222);")
        self.btn_predict.setObjectName("btn_predict")
        self.btn_predict.clicked.connect(self.prediction)
        self.lbl_ans = QtWidgets.QLabel(self.centralwidget)
        self.lbl_ans.setGeometry(QtCore.QRect(250, 370, 291, 21))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(False)
        font.setWeight(50)
        self.lbl_ans.setFont(font)
        self.lbl_ans.setObjectName("lbl_ans")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(170, 140, 461, 71))
        font = QtGui.QFont()
        font.setPointSize(14)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.imgPath = QtWidgets.QLineEdit(self.centralwidget)
        self.imgPath.setGeometry(QtCore.QRect(250, 250, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.imgPath.setFont(font)
        self.imgPath.setReadOnly(True)
        self.imgPath.setObjectName("imgPath")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Flower Recognition"))
        self.label_2.setText(_translate("MainWindow", "AI Semester Project"))
        self.btn_choose.setText(_translate("MainWindow", "Choose Image"))
        self.btn_predict.setText(_translate("MainWindow", "Predict Image"))
        self.lbl_ans.setText(_translate("MainWindow", "Selected Flower is: Select an Image"))
        self.label_3.setText(_translate("MainWindow", "Group members:    Member1  &  Member2"))
        self.imgPath.setText(_translate("MainWindow", "Path of the image"))
    

    def open_fileDialog(self):
        self.lbl_ans.setText("Selected Flower is: Select an Image")
        self.filename = QFileDialog.getOpenFileName()
        self.imgPath.setText(self.filename[0])
    
    def prediction(self):
        if self.filename == "":
            self.lbl_ans.setText("Selected Flower is: Select an Image")
        else:
            my_model = tf.keras.models.load_model("my_model")
            test_image = image.load_img(self.filename[0],target_size=(224,224))
            test_image = image.img_to_array(test_image)
            test_image = np.expand_dims(test_image,axis=0)
            result = my_model.predict(test_image)

            if result[0][0]==1:
                self.lbl_ans.setText("Selected Flower is:  Daisy")
            elif result[0][1]==1:
                self.lbl_ans.setText("Selected Flower is:  Dandelion")
            elif result[0][2]==1:
                self.lbl_ans.setText("Selected Flower is:  Rose")
            elif result[0][3]==1:
                self.lbl_ans.setText("Selected Flower is:  SunFlower")
            elif result[0][4]==1:
                self.lbl_ans.setText("Selected Flower is:  Tulip")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
